general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font" }
bold = { family = "FiraCode Nerd Font" }
italic = { family = "FiraCode Nerd Font" }
offset.y = 7
glyph_offset.y = 3
size = 11.25

[window]
padding.x = 10
padding.y = 10
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
