#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
ln -sf $DOTFILES/tmux/tmux.win.conf $HOME/.tmux.win.conf

ln -sf $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

rm -rf $HOME/.config/opencode/opencode.json
ln -s $DOTFILES/opencode/opencode.json $HOME/.config/opencode/opencode.json

rm -rf $HOME/.config/opencode/AGENTS.md
ln -s $DOTFILES/opencode/AGENTS.md $HOME/.config/opencode/AGENTS.md

rm -rf $HOME/.config/zsh.d
ln -s $DOTFILES/zsh.d $HOME/.config/zsh.d

rm -rf $HOME/.config/agents
ln -s $DOTFILES/agents $HOME/.config/agents
